### PR TITLE
SCIP release candidate 8.0.0rc19

### LINKED ISSUE #11: Soplex.exe not available on Windows
Soplex executable is not build for Windows. It is build for Unix so it would be nice to have it as well for Windows.

Preliminary discussion in #5:

@fschloesser said:
>It looks like boost `program_options` is not found, which means that the soplex executable cannot be built. It also warns about this in the [windows output](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=313258&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=600)
>
> ```
> CMake Warning at soplex/CMakeLists.txt:170 (message):
> Boost could not be found! ONLY the SoPlex library can be built without
> Boost.  The SoPlex binary will NOT be built.  If you require the binary,
> please make sure Boost is installed and your BOOST_ROOT environment
> variable is set.
> ```

@AntoinePrv said:
> Interestingly, we have afterwards
> ```
> -- Found Boost: D:/bld/scipoptsuite_1620141112358/_h_env/Library/lib/cmake/Boost-1.72.0/BoostConfig.cmake (found > version "1.72.0")  missing components: iostreams serialization program_options
> ```
> Looking into the [win-64/boost-cpp-1.72.0-hd4e6614_3.tar.bz2](https://anaconda.org/conda-forge/boost-cpp/1.72.0n/download/win-64/boost-cpp-1.72.0-hd4e6614_3.tar.bz2) package, I can see the following files (and similarily for serialization and iostream)
> ```
> Library/bin/boost_program_options.dll
> Library/include/boost/program_options.hpp
> Library/lib/boost_program_options.lib
> Library/lib/cmake/boost_program_options-1.72.0/boost_program_options-config-version.cmake
> Library/lib/cmake/boost_program_options-1.72.0/boost_program_options-config.cmake
> Library/lib/cmake/boost_program_options-1.72.0/libboost_program_options-variant-shared.cmake
> ```
> So I wonder why it is not finding it...

### PR DESCRIPTION
**Pull request by AntoinePrv**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] ~Bumped the build number (if the version is unchanged)~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Additional changes:
* Fix #11
* Fix #16

### CODE REVIEW

**Comment by AntoinePrv** [comment]
Most errors seem to be linked to the packaging, except on Windows were I believe there is a compilation error.
We have an error in the [build](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=419789&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=4513) around line `4513`. @fschloesser is there any error you might recognize?
```
d:\bld\scipoptsuite_1638241429452\_h_env\library\include\tbb\concurrent_vector.h(680): error C2061: syntax error: identifier 'concurrent_vector<`template-type-parameter-1',`template-type-parameter-2'>'
d:\bld\scipoptsuite_1638241429452\_h_env\library\include\tbb\concurrent_vector.h(1167): note: see reference to class template instantiation 'tbb::concurrent_vector<T,A>' being compiled
%PREFIX%\Library\include\boost/multiprecision/rational_adaptor.hpp(209): note: see reference to class template instantiation 'boost::rational<boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0,0,boost::multiprecision::signed_magnitude,boost::multiprecision::unchecked,std::allocator<boost::multiprecision::limb_type>>,boost::multiprecision::et_on>>' being compiled
%PREFIX%\Library\include\boost/multiprecision/number.hpp(1982): note: see reference to class template instantiation 'boost::multiprecision::backends::rational_adaptor<boost::multiprecision::backends::cpp_int_backend<0,0,boost::multiprecision::signed_magnitude,boost::multiprecision::unchecked,std::allocator<boost::multiprecision::limb_type>>>' being compiled
d:\bld\scipoptsuite_1638241429452\work\scipoptsuite\soplex\src\soplex/spxdefines.h(451): note: see reference to class template instantiation 'boost::multiprecision::number<boost::multiprecision::cpp_rational_backend,boost::multiprecision::et_on>' being compiled
%PREFIX%\Library\include\boost/math/constants/constants.hpp(273): note: see reference to class template instantiation 'boost::math::constants::detail::constant_half<T>' being compiled
        with
        [
            T=double
        ]
%PREFIX%\Library\include\boost/math/constants/constants.hpp(273): note: see reference to function template instantiation 'double boost::math::constants::half<T,boost::math::policies::policy<boost::math::policies::default_policy,boost::math::policies::default_policy,boost::math::policies::default_policy,boost::math::policies::default_policy,boost::math::policies::default_policy,boost::math::policies::default_policy,boost::math::policies::default_policy,boost::math::policies::default_policy,boost::math::policies::default_policy,boost::math::policies::default_policy,boost::math::policies::default_policy,boost::math::policies::default_policy,boost::math::policies::default_policy>>(void) noexcept' being compiled
        with
        [
            T=double
        ]
%PREFIX%\Library\include\boost/math/special_functions/detail/bernoulli_details.hpp(82): note: see reference to function template instantiation 'double boost::math::constants::half<double>(void) noexcept' being compiled
d:\bld\scipoptsuite_1638241429452\_h_env\library\include\tbb\concurrent_vector.h(681): error C2334: unexpected token(s) preceding ':'; skipping apparent function body
d:\bld\scipoptsuite_1638241429452\_h_env\library\include\tbb\concurrent_vector.h(61): fatal error C1075: '{': no matching token found
NMAKE : fatal error U1077: 'D:\bld\scipoptsuite_1638241429452\_build_env\Library\bin\cmake.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
```

**Comment by fschloesser** [comment]
Hey, in understand that you take out the tbb install lines, but why do you remove the tbb find module?

**Comment by AntoinePrv** [comment]
It is not needed, no? TBB is built with CMake (at least on Conda) so there is a `tbb-config.cmake` in the tbb package that define all the library targets.

**Comment by fschloesser** [comment]
Oh yea, i see. :+1:

**Comment by fschloesser** [comment]
FYI: @AntoinePrv we removed the packaging of libtbb.dll by default

**Comment by fschloesser** [comment]
So the problem with the windows job seems to be that it is missing fmt? (maybe it's a problem with the msvc? We are compiling with vs15 2017, can this help by any chance? )

**Comment by AntoinePrv** [comment]
> So the problem with the windows job seems to be that it is missing fmt? (maybe it's a problem with the msvc? We are compiling with vs15 2017, can this help by any chance? )

I think this was an omission on my end. Let's see if the test passes.

**Pull request merged**
