### PR TITLE
osx arm64 support

### PR DESCRIPTION
**Pull request by jurgen-lentz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jurgen-lentz** [comment]
@conda-forge-admin, please rerender

**Comment by jurgen-lentz** [comment]
@conda-forge-admin, please rerender

**Comment by jurgen-lentz** [comment]
I think arm64 fails at the moment because of ZIMPL. ZIMPL’s cmake uses the executables of bison and flex to output their versions but due to croos-compilation the executables cannot run. Is it possible to skip arm64 for ZIMPL so we can investigate even further what needs to be fixed @AntoinePrv ? Maybe with
```
build:
      # zimpl is not built in Windows since gmp is not available on 
      # conda-forge so this test is skipped. Details were left for 
      # the path to zimpl if we find a solution in the future.  
      skip: True  # [win and arm64]
```
?

**Comment by fschloesser** [comment]
I can see that this would not work, we could try to install brew and see if it works then. otherwise just deactivating zimpl should be fine. i will check this for the next release also

**Comment by jurgen-lentz** [comment]
@conda-forge-admin, please rerender

**Comment by jurgen-lentz** [comment]
> I can see that this would not work, we could try to install brew and see if it works then. otherwise just deactivating zimpl should be fine. i will check this for the next release also

I will try some changes out to see what we need to improve until the next release 👍

**Comment by jurgen-lentz** [comment]
@conda-forge-admin, please rerender

**Comment by jurgen-lentz** [comment]
I have only disabled gnuplot and ZIMPL for arm64. ZIMPL should be able to build on conda-forge for arm64 with the next release. Ready to be merged.

**Review by AntoinePrv — APPROVED** [review]

**Comment by AntoinePrv** [comment]
@jurgen-lentz , would you mind sending a similar PR to https://github.com/conda-forge/pyscipopt-feedstock?

**Comment by jurgen-lentz** [comment]
Yes, I will try to do that in the next days 👍

**Comment by dg0yt** [comment]
Is it possible to re-enable ZIMPL?

**Pull request merged**
