### PR TITLE
Enable gmp and zimpl for windows

### PR DESCRIPTION
**Pull request by dg0yt**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dg0yt** [comment]
win64:
~~~
SoPlex version 6.0.4 [mode: optimized] [precision: 8 byte] [rational: MPIR 3.0.0] [PaPILO  2.1.4 {ee0677c4}]
~~~

**Comment by dg0yt** [comment]
~~~
  "zimpl-3.5.3-h4dfd0cc": {
    "recipe": {
      "c_compiler": "vs2019",
      "channel_targets": "conda-forge main",
      "target_platform": "win-64",
      "zlib": "1.2"
    }
  }
~~~

**Review by AntoinePrv — APPROVED** [review]

**Comment by AntoinePrv** [comment]
@conda-forge-admin, please rerender

**Comment by AntoinePrv** [comment]
@dg0yt thanks for all your PRs! Are you interested in co-maintaining this feedstock?

**Comment by dg0yt** [comment]
> thanks for all your PRs! Are you interested in co-maintaining this feedstock?

Thanks for the offer @AntoinePrv. I have no private capacity for explicit commitments. My personal overlap with condaforge and sciptoptsuite is low, but there is a job-related link. These contributions were an opportunity for learning ;-) Feel free to GH-mention me for packaging/cross-platform/cmake/AZP issues.

**Pull request merged**
