### PR TITLE
Update recipe for 9.0.1

### PR DESCRIPTION
**Pull request by ju-manns**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Review by AntoinePrv — APPROVED** [review]

**Comment by ju-manns** [comment]
@conda-forge-admin, please rerender

**Comment by AntoinePrv** [comment]
@ju-manns I let your merge here when you're done.

**Comment by ju-manns** [comment]
> @ju-manns I let your merge here when you're done.

It says "Only those with write access to this repository can merge pull requests." Can you check again if I am missing some priviliges?

**Comment by AntoinePrv** [comment]
You're listed in the recipe and on the ReadMe. Maybe there is an invitation you need to reply to?
In the meantime should I merge this one?

**Comment by ju-manns** [comment]
> You're listed in the recipe and on the ReadMe. Maybe there is an invitation you need to reply to? In the meantime should I merge this one?

There was indeed an invitation that somehow ended up in the spam folder 😁

**Pull request merged**
