### PR TITLE
update recipe/meta.yaml for 802 release

### PR DESCRIPTION
**Pull request by fschloesser**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by fschloesser** [comment]
@conda-forge-admin please rerender

**Comment by fschloesser** [comment]
@conda-forge-admin please rerender

**Comment by AntoinePrv** [comment]
Hi @fschloesser, how is it going with the conda recipes? Everything working as you need?

**Comment by fschloesser** [comment]
Hey @AntoinePrv , thanks for checking in! Yes, everything looks good, we're finalizing the next bugfix release at the moment and I wanted to be on top of any potential errors here.

**Pull request merged**
