### PR TITLE
Add gnuplot to GCG

### PR DESCRIPTION
**Pull request by jurgen-lentz**
Hallo @AntoinePrv, 

I am a member of the GCG dev team and we thank you for adding GCG to conda-forge.
GCG uses [gnuplot](https://github.com/conda-forge/gnuplot-feedstock) to visualize decompositions. Can you please take a look at this PR if it satisfies all requirements?

Kind regards,
Jurgen Lentz

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jurgen-lentz** [comment]
@conda-forge-admin, please rerender

**Comment by AntoinePrv** [comment]
Thank you @jurgen-lentz for pointing this out!

Are there any other CMake flags (in `build.sh`) that need to be activated for this to work?

**Comment by jurgen-lentz** [comment]
We only use the CLI of gnuplot to create visualizations, so no :)

**Comment by AntoinePrv** [comment]
Ok, makes sense. Is this something you use in an executable/script packaged in GCG, or as a post-processing step (in which case maybe we should leave it out)?

**Comment by jurgen-lentz** [comment]
GCG runs in its C/C++ code the command 
```
gnuplot {filename}.gp
``` 
to run the executable of gnuplot.

**Comment by AntoinePrv** [comment]
Sounds good to me. We happen to have another branch for the SCIP8 release that required quite a refactor.
If you don't see any objection, I'll add it there and release it along with SCIP8.

**Comment by jurgen-lentz** [comment]
Sure. Thank you!

**Pull request closed without merging**
