### PR TITLE
Drop gnuplot for gcg

### PR DESCRIPTION
**Pull request by jurgen-lentz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Gnuplot is the only dependency of scipoptsuite that doesn't support macOS arm64 on conda ([see here](https://conda-forge.org/status/#armosxaddition)). To see if the scipoptsuite builds on macOS arm64 on conda, we should drop gnuplot for gcg for now and add it again when gnuplot supports macOS arm64 on conda.

### CODE REVIEW

**Comment by fschloesser** [comment]
@conda-forge-admin, please rerender

**Comment by fschloesser** [comment]
I don't know if @AntoinePrv has some knowledge to share here, but I think this should be fine and can be merged.

**Comment by AntoinePrv** [comment]
Code wise it looks good to me. What is the rational w.r.t. the opposite PR #22 ?

**Comment by jurgen-lentz** [comment]
> Code wise it looks good to me. What is the rational w.r.t. the opposite PR #22 ?

Gnuplot is the only dependency of scipoptsuite that doesn‘t build on [arm osx](https://conda-forge.org/status/#armosxaddition) on conda. Unfortunately, gnuplot has had this problem for quite some time (see [here](https://github.com/conda-forge/gnuplot-feedstock/pulls)). In my opinion, we should drop gnuplot as dependency for now to test if scipoptsuite builds on arm osx on conda. We can add gnuplot back, when gnuplot supports arm osx on conda. @AntoinePrv Or is it possible to specify that gnuplot shouldn‘t be used when scipoptsuite is built on arm osx?

**Comment by AntoinePrv** [comment]
It is possible to use the [selectors](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#preprocessing-selectors), but I don't know whether it will be enough to receive the automated PR for MacOS Arm64.

We could either:
 - Wait for `gnuplot` to be fully available;
 - Drop `gnuplot` (I'm also not sure how long it will take the system to realize that and send a PR);
 - Drop `gnuplot` for MacOS Arm64 and manually create the PR.
 
 @fschloesser Is `scipoptsuite` ready for MacOS Arm64?

**Comment by jurgen-lentz** [comment]
@AntoinePrv Then, I would prefer the third option (Drop `gnuplot` for MacOS Arm64 and manually create the PR.).

I have built successfully the `scipoptsuite` on my MacOS arm64 (not on conda-forge) but have not tried to build it with `cliquer`, `ipopt` and `quadmath` yet.
I think we should at least give it a try, so we can see how much work is needed to support MacOS arm64 on conda-forge for the `scipoptsuite`.

**Comment by jurgen-lentz** [comment]
@conda-forge-admin please rerender

**Comment by jurgen-lentz** [comment]
I have done it on the new MR #27. I will close this MR.

**Pull request closed without merging**
